# This configuration file should contain all required configuration parameters
# for the phylogenetic workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

filter:
  exclude: "defaults/dropped_strains.txt"
  group_by: "country year"
  sequences_per_group: 2

tree:
  method: "iqtree"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_rate: 0.0006

ancestral:
  inference: "joint"

traits:
  columns: "country"

export:
  auspice_config: "defaults/auspice_config.json"
  colors: "defaults/colors.tsv"
